<<<<<<< HEAD
# Generated by Django 4.0.2 on 2022-03-19 20:53
=======
# Generated by Django 4.0.1 on 2022-02-09 06:21
>>>>>>> 43b08a4b2c6cac0e38c02e002d5c6c999c8ba9de

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.IntegerField()),
                ('report_info', models.CharField(max_length=1000)),
                ('doctor_id', models.IntegerField()),
                ('patient_id', models.IntegerField()),
                ('lab_staff_id', models.IntegerField()),
                ('report_status', models.CharField(max_length=100)),
            ],
        ),
<<<<<<< HEAD
=======
        migrations.CreateModel(
            name='LabStaffDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_staff_id', models.IntegerField()),
                ('lab_staff_name', models.CharField(max_length=100)),
            ],
        ),
>>>>>>> 43b08a4b2c6cac0e38c02e002d5c6c999c8ba9de
    ]
