# Generated by Django 4.0.3 on 2022-03-29 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.IntegerField(default=0)),
                ('report_info', models.CharField(max_length=5000, null=True)),
                ('doctor_id', models.IntegerField()),
                ('patient_id', models.IntegerField()),
                ('lab_staff_id', models.IntegerField()),
                ('report_status', models.CharField(max_length=100)),
                ('tests', models.TextField(max_length=1000, null=True)),
            ],
        ),
    ]
