# Generated by Django 4.0.1 on 2022-03-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabStaff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labreports',
            name='id',
        ),
        migrations.AlterField(
            model_name='labreports',
            name='report_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
