# Generated by Django 4.0.1 on 2022-02-13 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LabStaff', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LabStaffDetails',
        ),
    ]
