# Generated by Django 4.0.1 on 2022-03-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabStaff', '0002_delete_labstaffdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreports',
            name='request_status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
