# Generated by Django 4.0.1 on 2022-03-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabStaff', '0003_labreports_request_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labreports',
            name='id',
        ),
        migrations.AlterField(
            model_name='labreports',
            name='report_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
