# Generated by Django 4.0.1 on 2022-03-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabStaff', '0003_remove_labreports_tests_labreports_test_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreports',
            name='patient_diagnosis',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
