# Generated by Django 4.0.1 on 2022-03-16 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LabStaff', '0004_remove_labreports_id_alter_labreports_report_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LabReports',
        ),
    ]
