# Generated by Django 4.0.1 on 2022-03-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LabStaff', '0005_delete_labreports'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReports',
            fields=[
                ('report_id', models.IntegerField(primary_key=True, serialize=False)),
                ('report_info', models.CharField(max_length=1000)),
                ('doctor_id', models.IntegerField()),
                ('patient_id', models.IntegerField()),
                ('lab_staff_id', models.IntegerField()),
                ('report_status', models.CharField(max_length=100)),
                ('request_status', models.CharField(default='Pending', max_length=100)),
            ],
        ),
    ]
