# Generated by Django 4.0.1 on 2022-03-16 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LabStaff', '0008_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LabReports',
        ),
    ]
