# Generated by Django 4.0.1 on 2022-03-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LabStaff', '0009_delete_labreports'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_info', models.CharField(max_length=1000)),
                ('doctor_id', models.IntegerField()),
                ('patient_id', models.IntegerField()),
                ('lab_staff_id', models.IntegerField()),
                ('report_status', models.CharField(max_length=100)),
                ('request_status', models.CharField(default='Pending', max_length=100)),
            ],
        ),
    ]
