# Generated by Django 4.0.1 on 2022-03-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_remove_staffdetails_id_alter_staffdetails_staff_dept_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_first_name', models.CharField(max_length=255)),
                ('employee_last_name', models.CharField(max_length=255)),
                ('employee_dept', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='StaffDetails',
        ),
    ]
