# Generated by Django 4.0.1 on 2022-02-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceStaffDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_staff_id', models.IntegerField()),
                ('insurance_staff_name', models.CharField(max_length=100)),
                ('patient_id', models.IntegerField()),
                ('insurance_name', models.CharField(max_length=100)),
                ('claim_status', models.CharField(max_length=100)),
                ('claim_amt', models.IntegerField(max_length=100)),
            ],
        ),
    ]
