# Generated by Django 4.0.2 on 2022-03-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceClaimDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_staff_id', models.IntegerField()),
                ('patient_id', models.IntegerField()),
                ('insurance_name', models.CharField(max_length=100)),
                ('claim_status', models.CharField(max_length=100)),
                ('claim_amt', models.IntegerField()),
            ],
        ),
    ]
