# Generated by Django 4.0.1 on 2022-02-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsuranceStaff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancestaffdetails',
            name='claim_amt',
            field=models.IntegerField(),
        ),
    ]
