# Generated by Django 4.0.3 on 2022-03-29 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentDetails',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_id', models.IntegerField()),
                ('first_name', models.CharField(default='fn', max_length=255)),
                ('last_name', models.CharField(default='ln', max_length=255)),
                ('doctor_id', models.IntegerField(default=0)),
                ('requested_date', models.DateField(blank=True, null=True)),
                ('prescribed_report_status', models.BooleanField(default=False)),
                ('report_status', models.CharField(default='Pending', max_length=255)),
                ('status', models.CharField(default='Pending', max_length=255)),
                ('patient_diagnosis', models.CharField(default='adding....', max_length=255)),
            ],
        ),
    ]
