# Generated by Django 4.0.2 on 2022-03-15 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalStaff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentdetails',
            name='requested_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
