# Generated by Django 4.0.1 on 2022-02-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalStaff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.IntegerField()),
                ('start_dt_time', models.DateTimeField()),
                ('end_dt_time', models.DateTimeField()),
                ('doctor_id', models.IntegerField()),
                ('patient_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('patient_id', models.IntegerField()),
                ('transaction_info', models.CharField(max_length=100)),
                ('transaction_status', models.CharField(max_length=100)),
                ('receipt_info', models.CharField(max_length=100)),
            ],
        ),
    ]
