# Generated by Django 4.0.2 on 2022-03-15 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalStaff', '0002_alter_appointmentdetails_requested_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentdetails',
            name='status',
            field=models.CharField(default='Pending', max_length=255),
        ),
    ]
