# Generated by Django 4.0.2 on 2022-03-19 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalStaff', '0003_appointmentdetails_status'),
        ('HospitalStaff', '0003_delete_hospitalstaffdetails_and_more'),
    ]

    operations = [
    ]
