# Generated by Django 4.0.2 on 2022-03-19 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalStaff', '0004_merge_20220319_2227'),
        ('HospitalStaff', '0004_merge_20220319_2228'),
    ]

    operations = [
    ]
