# Generated by Django 4.0.2 on 2022-03-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalStaff', '0005_merge_20220319_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentdetails',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='appointmentdetails',
            name='end_dt_time',
        ),
        migrations.RemoveField(
            model_name='appointmentdetails',
            name='start_dt_time',
        ),
        migrations.AddField(
            model_name='appointmentdetails',
            name='appointment_with',
            field=models.CharField(default='General Appointmemnt', max_length=255),
        ),
        migrations.AddField(
            model_name='appointmentdetails',
            name='first_name',
            field=models.CharField(default='fn', max_length=255),
        ),
        migrations.AddField(
            model_name='appointmentdetails',
            name='last_name',
            field=models.CharField(default='ln', max_length=255),
        ),
    ]
