<<<<<<< HEAD
# Generated by Django 4.0.2 on 2022-03-19 20:53

from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 4.0.1 on 2022-02-09 06:21

from django.db import migrations, models
>>>>>>> 43b08a4b2c6cac0e38c02e002d5c6c999c8ba9de


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('Doctors', '0001_initial'),
=======
>>>>>>> 43b08a4b2c6cac0e38c02e002d5c6c999c8ba9de
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(default=0)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_age', models.IntegerField()),
                ('patient_weight', models.CharField(max_length=100)),
                ('patient_height', models.CharField(max_length=100)),
                ('patient_address', models.CharField(max_length=1000)),
                ('patient_phone_no', models.IntegerField()),
<<<<<<< HEAD
                ('patient_email', models.EmailField(max_length=254, null=True)),
                ('patient_disease', models.CharField(max_length=1000)),
=======
                ('patient_disease', models.CharField(max_length=1000)),
                ('doctor_id', models.IntegerField()),
>>>>>>> 43b08a4b2c6cac0e38c02e002d5c6c999c8ba9de
                ('insurance_id', models.IntegerField()),
                ('patient_diagnosis', models.CharField(max_length=1000)),
                ('patient_reports', models.CharField(max_length=1000)),
                ('patient_prescription', models.CharField(max_length=1000)),
<<<<<<< HEAD
                ('doctor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Doctors.doctordetails')),
=======
>>>>>>> 43b08a4b2c6cac0e38c02e002d5c6c999c8ba9de
            ],
        ),
    ]
