# Generated by Django 4.0.2 on 2022-03-19 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(default=0)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_age', models.IntegerField()),
                ('patient_weight', models.CharField(max_length=100)),
                ('patient_height', models.CharField(max_length=100)),
                ('patient_address', models.CharField(max_length=1000)),
                ('patient_phone_no', models.IntegerField()),
                ('patient_email', models.EmailField(max_length=254, null=True)),
                ('patient_disease', models.CharField(max_length=1000)),
                ('insurance_id', models.IntegerField()),
                ('patient_diagnosis', models.CharField(max_length=1000)),
                ('patient_reports', models.CharField(max_length=1000)),
                ('patient_prescription', models.CharField(max_length=1000)),
                ('doctor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Doctors.doctordetails')),
            ],
        ),
    ]
