# Generated by Django 4.0.1 on 2022-02-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(default=0)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_age', models.IntegerField()),
                ('patient_weight', models.CharField(max_length=100)),
                ('patient_height', models.CharField(max_length=100)),
                ('patient_address', models.CharField(max_length=1000)),
                ('patient_phone_no', models.IntegerField()),
                ('patient_disease', models.CharField(max_length=1000)),
                ('doctor_id', models.IntegerField()),
                ('insurance_id', models.IntegerField()),
                ('patient_diagnosis', models.CharField(max_length=1000)),
                ('patient_reports', models.CharField(max_length=1000)),
                ('patient_prescription', models.CharField(max_length=1000)),
            ],
        ),
    ]
