# Generated by Django 4.0.1 on 2022-02-13 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0002_alter_doctordetails_doctor_id'),
        ('Patients', '0002_remove_patientdetails_doctor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='doctor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Doctors.doctordetails'),
        ),
    ]
