# Generated by Django 4.0.2 on 2022-03-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.IntegerField(default=0)),
                ('doctor_name', models.CharField(max_length=1000)),
                ('doctor_spec', models.CharField(max_length=1000)),
            ],
        ),
    ]
