# Generated by Django 4.0.1 on 2022-03-29 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labtests',
            old_name='lab_Tests',
            new_name='lab_test',
        ),
    ]
